/**
 * Supabase Database Types
 *
 * This file will be auto-generated by Supabase CLI after running:
 * npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts
 *
 * For now, we provide a placeholder structure that matches our planned schema.
 * Replace this with auto-generated types once Supabase is connected.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      scooter_models: {
        Row: {
          id: string;
          name: string;
          slug: string;
          tagline: string | null;
          description: string | null;
          image_url: string | null;
          sort_order: number;
          status: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          tagline?: string | null;
          description?: string | null;
          image_url?: string | null;
          sort_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          tagline?: string | null;
          description?: string | null;
          image_url?: string | null;
          sort_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      variants: {
        Row: {
          id: string;
          model_id: string;
          name: string;
          price: number;
          range_km: number;
          top_speed: number;
          battery: string;
          charging_time: string;
          motor_power: string;
          boot_space: number | null;
          specs: Json;
          sort_order: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          model_id: string;
          name: string;
          price: number;
          range_km: number;
          top_speed: number;
          battery: string;
          charging_time: string;
          motor_power: string;
          boot_space?: number | null;
          specs?: Json;
          sort_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          model_id?: string;
          name?: string;
          price?: number;
          range_km?: number;
          top_speed?: number;
          battery?: string;
          charging_time?: string;
          motor_power?: string;
          boot_space?: number | null;
          specs?: Json;
          sort_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      colors: {
        Row: {
          id: string;
          variant_id: string;
          name: string;
          hex_code: string;
          image_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          variant_id: string;
          name: string;
          hex_code: string;
          image_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          variant_id?: string;
          name?: string;
          hex_code?: string;
          image_url?: string | null;
          created_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          city: string;
          model_id: string | null;
          message: string | null;
          source: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone: string;
          city: string;
          model_id?: string | null;
          message?: string | null;
          source?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          city?: string;
          model_id?: string | null;
          message?: string | null;
          source?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      test_ride_bookings: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          dealer_id: string;
          model_id: string | null;
          booking_date: string;
          time_slot: string;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone: string;
          dealer_id: string;
          model_id?: string | null;
          booking_date: string;
          time_slot: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          dealer_id?: string;
          model_id?: string | null;
          booking_date?: string;
          time_slot?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      dealers: {
        Row: {
          id: string;
          name: string;
          address: string;
          city: string;
          state: string;
          pincode: string;
          phone: string;
          email: string | null;
          latitude: number;
          longitude: number;
          timings: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          address: string;
          city: string;
          state: string;
          pincode: string;
          phone: string;
          email?: string | null;
          latitude: number;
          longitude: number;
          timings?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string;
          city?: string;
          state?: string;
          pincode?: string;
          phone?: string;
          email?: string | null;
          latitude?: number;
          longitude?: number;
          timings?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          excerpt: string | null;
          content: string;
          cover_image: string | null;
          category: string | null;
          author: string | null;
          is_published: boolean;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          excerpt?: string | null;
          content: string;
          cover_image?: string | null;
          category?: string | null;
          author?: string | null;
          is_published?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          excerpt?: string | null;
          content?: string;
          cover_image?: string | null;
          category?: string | null;
          author?: string | null;
          is_published?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      faqs: {
        Row: {
          id: string;
          question: string;
          answer: string;
          category: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          question: string;
          answer: string;
          category: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          question?: string;
          answer?: string;
          category?: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

// Specific table types
export type ScooterModel = Tables<'scooter_models'>;
export type Variant = Tables<'variants'>;
export type Color = Tables<'colors'>;
export type Lead = Tables<'leads'>;
export type TestRideBooking = Tables<'test_ride_bookings'>;
export type Dealer = Tables<'dealers'>;
export type BlogPost = Tables<'blog_posts'>;
export type FAQ = Tables<'faqs'>;
